name: 'AutoUpdate PRs'
author: 'Alexander Bauer <contact@alexander-bauer.de>'
description: 'A GitHub Action that auto-updates PRs with changes from their destination branch.'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'git-pull-request'
  color: 'blue'
