name: Tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - name: Install dependencies
        run: npm ci
      - name: Lint files
        run: npm run lint
      - name: Run tests
        run: npm test
        env:
          CI: true
      - name: Upload coverage
        uses: codecov/codecov-action@v3
